### PR TITLE
Update start

### PR DESCRIPTION
**Pull request by veeramarni**
``if [ "$CHECKOUT" ]; then`` doesn't work, it should be  ``if [ "$CHECKOUT" = true ]; then`` or ``if $CHECKOUT; then``

### CODE REVIEW

**Comment by veeramarni** [comment]
``if [ "$CHECKOUT" ]; then`` doesn't work, it should be  ``if [ "$CHECKOUT" = true ]; then`` or ``if $CHECKOUT; then``

**Comment by cmather** [comment]
Oh cool thanks for this! Is it `==` or `=`

**Comment by veeramarni** [comment]
It is ``=``

**Comment by cmather** [comment]
Many thanks

**Pull request merged**
